# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2020-03-13 15:32


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eolzoomauth',
            old_name='zoom_id',
            new_name='zoom_refresh_token',
        ),
    ]
