# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 19:23


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0005_auto_20200428_1903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EolZoomRegistrants',
            new_name='EolZoomRegistrant',
        ),
    ]
