# Generated by Django 2.2.13 on 2020-08-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0007_eolgoogleauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolgoogleauth',
            name='channel_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eolgoogleauth',
            name='livebroadcast_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
