# Generated by Django 2.2.13 on 2020-08-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0010_eolzoommappingusermeet'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='broadcast_ids',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='title',
            field=models.CharField(default='', max_length=250),
        ),
    ]
