# Generated by Django 2.2.13 on 2020-08-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0011_auto_20200818_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eolzoommappingusermeet',
            name='broadcast_ids',
            field=models.CharField(default='', max_length=255),
        ),
    ]
