# Generated by Django 2.2.13 on 2020-08-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0012_auto_20200819_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
