# Generated by Django 2.2.19 on 2021-04-29 20:45

from django.db import migrations, models
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0014_eolgoogleauth_custom_live_streaming_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='course_key',
            field=opaque_keys.edx.django.models.CourseKeyField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='restricted_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eolzoommappingusermeet',
            name='usage_hey',
            field=opaque_keys.edx.django.models.UsageKeyField(default=None, max_length=255),
        ),
    ]
