# Generated by Django 2.2.19 on 2021-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eolzoom', '0015_auto_20210429_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eolzoommappingusermeet',
            old_name='usage_hey',
            new_name='usage_key',
        ),
    ]
